# Based on openjdk:8, already includes lein
image: clojure:lein-2.8.1
# If you need to configure a database, add a `services` section here
# See https://docs.gitlab.com/ce/ci/services/postgres.html
# Make sure you configure the connection as well

before_script:
  # If you need to install any external applications, like a 
  # postgres client, you may want to uncomment the line below:
  # 
  - apt-get update -y
  - apt install ocl-icd-opencl-dev -y
  - mkdir tmp
  - cd tmp
  - wget --referer=http://support.amd.com  https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.40-492261.tar.xz
  â€‹- tar -Jxvf amdgpu-pro-17.40-492261.tar.xz
  - cd amdgpu-pro-17.40-492261
  - amdgpu-pro-driver/amdgpu-pro-install
  #
  # Retrieve project dependencies
  # Do this on before_script since it'll be shared between both test and
  # any production sections a user adds
  - lein deps

test:
  script:
  # If you need to run any migrations or configure the database, this 
  # would be the point to do it.  
  - lein run -m hara.test exit